services:
  db:
    image: postgres:16
    container_name: ecom_postgres
    environment:
      POSTGRES_DB: ecom
      POSTGRES_USER: ecom
      POSTGRES_PASSWORD: ecom123
    ports:
      - "5432:5432"
    volumes:
      - ecom_pgdata:/var/lib/postgresql/data

volumes:
  ecom_pgdata: