server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    username: ecom
    password: ecom123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false