server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecom
    driver-class-name: org.postgresql.Driver
    username: ecom
    password: ecom123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    open-in-view: false

jwt:
  signerKey: "JeIrdzgaCqmzpSGq4pjO7YP90qhV+Gol0QJGGUDQyXkD/rA6frpMY7ADK8GU7V0K5LtoyJNa2jtTh+Q8EuwXNA=="
  valid-duration: 3600 # seconds
  refreshable-duration: 36000 # seconds